name: Deploy to Staging

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      build_params:
        description: "Build parameters"
        required: false
        type: string
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Setup TurboRepo remote cache
        uses: felixmosh/turborepo-gh-artifacts@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          server-token: ${{ secrets.TURBO_SERVER_TOKEN }}
      - name: Build packages and apps
        run: yarn build --api="http://127.0.0.1:9080" --token="${{ secrets.TURBO_SERVER_TOKEN }}" --team="foo" ${{ github.event.inputs.build_params }}
        env:
          BUILD_ENV: STAGING
          NOCO_API_URL: ${{ secrets.NOCO_API_URL }}
          NOCO_AUTH_TOKEN: ${{ secrets.NOCO_AUTH_TOKEN }}
          COMING_SOON: ${{ secrets.COMING_SOON }}
      - name: Deploy to Github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: staging.bkkelection2022.wevis.info
